### ISSUE TITLE
Certain reactions schemes will cause the script to yield errors.

### ISSUE THREAD

**Issue by shaqoatmeal420** [DocMinus/chem-rdf-fixer#7]
I mass downloaded reactions from scifinder and ended up getting a Unicode Decode Error: 

"'charmap' codec can't decode byte 0x81 in position 671: character maps to <undefined>".

My assumption is there is some sort of special character but looking at the position in the rdf file shows nothing of interest.

**Comment by DocMinus** [comment]
Hm, interesting. Sounds like an encoding issue. It might be trying to read utf-8 type and maybe your files were saved as a different encoding depending on your region? Does that happen with every file, or only certain ones?
 I don't supposed you could share a file (perhaps a "dummy" search if there is confidentiality)? You could share via the mail function, that should furthermore reduce any potential issues with Scifinder.

**Comment by shaqoatmeal420** [comment]
This is only a prelim work so I'm fine with sending the rdf file (attached).

The output still does give a "fixed" rdf file, but it cannot seem to give a
csv.

**Comment by DocMinus** [comment]
Maybe I am blind, but I don't see anything attached...?

**Comment by shaqoatmeal420** [comment]
Hmm, thats odd then because I can see it from my end (I’m not at work right now so it’s on my IPhone). I’m not sure gmail supports sending rdf files then, and I know for a fact that github doesn’t as I’ve tried. Do you have an alternative method to send it?On Jun 11, 2024, at 03:30, Alex M. ***@***.***> wrote:﻿
Maybe I am blind, but I don't see anything attached...?

**Comment by shaqoatmeal420** [comment]
It occurred to me that you are viewing this on github, which does not support rdf files and why I sent it via email, please check your inbox

**Comment by DocMinus** [comment]
That didn't work. Besides, come to think of it, I wouldn't open a file via email anyway.
I suggest the following option:
see if you can add the text content of the file via copy/paste into here. alternatively, create a pull request and have the file attached there.

**Comment by shaqoatmeal420** [comment]
[PhAz_alkyne501(txt).txt](https://github.com/user-attachments/files/15806885/PhAz_alkyne501.txt.txt)

I converted the file into a txt file to see if this can work, there's too much to paste into a comment. I will send the pull request if this doesn't work either

**Comment by DocMinus** [comment]
got it now.
will be busy the next few days, not sure when I can follow this up.

**Comment by shaqoatmeal420** [comment]
I'm in no rush

**Comment by DocMinus** [comment]
check this branch, it should work now.
https://github.com/DocMinus/chem-rdf-fixer/tree/fix/issue-%237
I will update the main branch and the pypi version the next few days.

**Comment by DocMinus** [comment]
Latest version now pushed to main and pypi updated.
